#!/usr/bin/env bash
# Write www/.env.local from Google Cloud Secret Manager (for local dev without a committed .env).
# Requires: gcloud auth login and gcloud config set project PROJECT_ID
# Usage: ./scripts/write-env-from-gcp.sh   or   just env

set -e

PROJECT_ID="${GOOGLE_CLOUD_PROJECT:-$(gcloud config get-value project 2>/dev/null)}"
if [ -z "$PROJECT_ID" ] || [ "$PROJECT_ID" = "undefined" ]; then
  PROJECT_ID="slides2gifcom"
fi

ENV_FILE="www/.env.local"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

echo "Writing $ENV_FILE from Secret Manager (project: $PROJECT_ID)"
echo ""

get_secret() {
  gcloud secrets versions access latest --secret="$1" --project="$PROJECT_ID" 2>/dev/null || echo ""
}

write_env() {
  local name=$1
  local value=$2
  if [ -n "$value" ]; then
    echo "${name}=${value}" >> "$ENV_FILE"
  fi
}

# Optional: backup existing
if [ -f "$ENV_FILE" ]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
  echo "Backed up existing to ${ENV_FILE}.bak"
fi

# Start fresh (so we don't mix old + new)
cat > "$ENV_FILE" << 'HEADER'
# Generated by scripts/write-env-from-gcp.sh — do not commit. Edit as needed.
HEADER

SECRET_COOKIE_PASSWORD=$(get_secret "secret-cookie-password")
OAUTH_CLIENT_ID=$(get_secret "oauth-client-id")
OAUTH_CLIENT_SECRET=$(get_secret "oauth-client-secret")
GCS_CACHE_BUCKET="${GCS_CACHE_BUCKET:-slides2gif-cache}"

write_env "SECRET_COOKIE_PASSWORD" "$SECRET_COOKIE_PASSWORD"
write_env "OAUTH_CLIENT_ID" "$OAUTH_CLIENT_ID"
write_env "OAUTH_CLIENT_SECRET" "$OAUTH_CLIENT_SECRET"
write_env "GCS_CACHE_BUCKET" "$GCS_CACHE_BUCKET"

# Optional Picker secrets (may not exist in every project)
GOOGLE_CLOUD_PROJECT_NUMBER=$(get_secret "google-cloud-project-number")
GOOGLE_PICKER_DEVELOPER_KEY=$(get_secret "google-picker-developer-key")
[ -n "$GOOGLE_CLOUD_PROJECT_NUMBER" ] && write_env "GOOGLE_CLOUD_PROJECT_NUMBER" "$GOOGLE_CLOUD_PROJECT_NUMBER"
[ -n "$GOOGLE_PICKER_DEVELOPER_KEY" ] && write_env "GOOGLE_PICKER_DEVELOPER_KEY" "$GOOGLE_PICKER_DEVELOPER_KEY"

if [ -z "$SECRET_COOKIE_PASSWORD" ] || [ -z "$OAUTH_CLIENT_ID" ]; then
  echo "Error: Required secrets (secret-cookie-password, oauth-client-id) not found or not accessible."
  echo "Run: gcloud auth login && gcloud config set project $PROJECT_ID"
  exit 1
fi

echo "Wrote $ENV_FILE"
echo "Run: just dev"
